catalog_name: users # Change this to the catalog you're using
schema_name: martijn_hofstra # Change this to the schema where the hotel reservations dataset resides

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - no_of_special_requests
  - avg_price_per_room
  - no_of_previous_bookings_not_canceled
  - no_of_previous_cancellations

cat_features:
  - type_of_meal_plan
  - required_car_parking_space
  - room_type_reserved
  - lead_time
  - repeated_guest
  - market_segment_type
  - arrival_date
  - arrival_month
  - arrival_year

target: booking_status
